name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build, push, and deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Master
      uses: actions/checkout@master
    - name: Show appsettings.json
      run: |
        cat $GITHUB_WORKSPACE/appsettings.json
    - name: Show updated Json
      run: |
        jq '.token = "testing"' $GITHUB_WORKSPACE/appsettings.json
    - name: Update appsettings.json
      run: |
        jq '.token = "testing"' $GITHUB_WORKSPACE/appsettings.json | sponge $GITHUB_WORKSPACE/appsettings.json
    - name: Show appsettings.json again
      run: |
        cat $GITHUB_WORKSPACE/appsettings.json
