name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build, push, and deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Master
      uses: actions/checkout@master
    - name: Update appsettings.json
      env: 
        ANILIST_TOKEN: testing
      run: |
        jq '.token = "${ANILIST_TOKEN}"' $GITHUB_WORKSPACE/appsettings.json > $GITHUB_WORKSPACE/appsettings.json
        cat $GITHUB_WORKSPACE/appsettings.json
        
