name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build, push, and deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Master
      uses: actions/checkout@master
    - name: Show appsettings.json
      run: |
        cat $GITHUB_WORKSPACE/appsettings.json
    - name: Show updated Json
      run: |
        jq '.token = "testing"' $GITHUB_WORKSPACE/appsettings.json
    - name: Update appsettings.json
      env: 
        ANILIST_TOKEN: ${{ secrets.ANILIST_TOKEN }}
      run: |
        jq '.token = "${ANILIST_TOKEN}"' $GITHUB_WORKSPACE/appsettings.json > $GITHUB_WORKSPACE/appsettings.json.temp && cp $GITHUB_WORKSPACE/appsettings.json.temp $GITHUB_WORKSPACE/appsettings.json 
    - name: Show appsettings.json again
      run: |
        cat $GITHUB_WORKSPACE/appsettings.json
