name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build, push, and deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Master
      uses: actions/checkout@master
    - name: Update appsettings.json
      run: jq '.token = "${{ secrets.ANILIST_TOKEN }}"' $GITHUB_WORKSPACE/appsettings.json > $GITHUB_WORKSPACE/appsettings.json.temp && cp $GITHUB_WORKSPACE/appsettings.json.temp $GITHUB_WORKSPACE/appsettings.json 
    - name: Show appsettings.json again
      run: |
        cat $GITHUB_WORKSPACE/appsettings.json
